name: random_color_switcher
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.16

flutter:
  uses-material-design: true
